# Basic configuration for LightningLens

project:
  name: 'LightningLens'
  version: '0.1.0'

# Data collection settings
data_collection:
  timeframe_hours: 24
  batch_size: 32
  collection_interval_minutes: 60

# Model parameters
model:
  # Random Forest parameters
  n_estimators: 100
  max_depth: 10
  min_samples_split: 2
  # Feature importance threshold
  feature_importance_threshold: 0.01
  # For future neural network implementation
  hidden_size: 64
  num_layers: 2
  dropout: 0.2
  sequence_length: 24

# Training parameters
training:
  learning_rate: 0.001
  batch_size: 32
  epochs: 50
  validation_split: 0.2
  early_stopping_patience: 5

# Rebalancing recommendations
rebalancing:
  threshold_pct: 10
  min_tx_value_sats: 10000
  max_tx_value_sats: 1000000
  fee_rate_limit_ppm: 500

# Paths
paths:
  raw_data: 'data/raw'
  processed_data: 'data/processed'
  models: 'data/models'
  logs: 'logs'
